- name: Download Zig tarball
  ansible.builtin.get_url:
    url: "{{ zig_base_url }}/{{ zig_version }}/{{ zig_file }}.tar.xz"
    dest: "/tmp/{{ zig_file }}.tar.xz"
    mode: '0644'

- name: Remove old Zig
  ansible.builtin.file:
    path: /usr/local/zig
    state: absent

- name: Extract Zig to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/{{ zig_file }}.tar.xz"
    dest: /usr/local
    remote_src: yes

- name: Rename Zig folder to /usr/local/zig
  ansible.builtin.command: mv "/usr/local/{{ zig_file }}" /usr/local/zig
  args:
    creates: /usr/local/zig

- name: Ensure Zig in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/zig.sh
    line: 'export PATH=$PATH:/usr/local/zig'
    create: yes
    mode: '0755'