---
- name: Set Zig OS and architecture
  set_fact:
    zig_os: "{{ zig_os_map[ansible_system] | default('linux') }}"
    zig_arch: "{{ zig_arch_map[ansible_architecture] | default('x86_64') }}"
    

- name: Set Zig Download URL File
  set_fact:
    zig_file: "zig-{{ zig_os }}-{{ zig_arch }}-{{ zig_version }}"

- name: Download Zig tarball
  ansible.builtin.get_url:
    url: "{{ zig_base_url }}/{{ zig_version }}/{{ zig_file }}.tar.xz"
    dest: "/tmp/{{ zig_file }}.tar.xz"
    mode: '0644'

- name: Remove old Zig
  ansible.builtin.file:
    path: /usr/local/zig
    state: absent

- name: Extract Zig tarball to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/{{ zig_file }}.tar.xz"
    dest: /usr/local
    remote_src: yes

- name: Rename Zig folder to /usr/local/zig
  ansible.builtin.command: mv "/usr/local/{{ zig_file }}" /usr/local/zig
  args:
    creates: /usr/local/zig

- name: Ensure Zig binary in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/zig.sh
    line: 'export PATH=$PATH:/usr/local/zig'
    create: yes
    mode: '0755'
