---
- name: Determine home directory for {{ ssh_user }}
  ansible.builtin.set_fact:
    ssh_home: "{{ '/root' if ssh_user == 'root' else '/home/' + ssh_user }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_home }}/.ssh"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: "0700"

- name: Add SSH keys to authorized_keys for {{ ssh_user }}
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('url', item) }}"
  loop: "{{ ssh_keys_urls }}"

