os: linux
architecture: amd64
base_dl_url: "https://go.dev/dl/go"
version: "1.24.5"

# Maps Ansible facts to Go's naming convention
go_os_map:
  Linux: linux
  Darwin: darwin
  Windows: windows

go_arch_map:
  x86_64: amd64
  aarch64: arm64
