- name: Set OS and architecture facts
  set_fact:
    go_os: "{{ go_os_map[ansible_system] | default('linux') }}"
    go_arch: "{{ go_arch_map[ansible_architecture] | default('amd64') }}"

- name: Set Go download URL fact
  set_fact:
    go_download_url: "{{ base_dl_url }}{{ version }}.{{ go_os }}-{{ go_arch }}.tar.gz"


- name: Download Go tarball
  ansible.builtin.get_url:
    url: "{{ go_download_url }}"
    dest: "/tmp/go{{ version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    mode: '0644'

- name: Remove old Go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Extract Go tarball to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/go{{ version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Ensure Go binary is in PATH (for all users)
  ansible.builtin.lineinfile:
    path: /etc/profile.d/go.sh
    line: 'export PATH=$PATH:/usr/local/go/bin'
    create: yes
    mode: '0755'