- name: Ensure the crb repository is enabled
  ansible.builtin.dnf:
    enablerepo: crb
  when: ansible_os_family == "RedHat"
  become: true

- name: Update package cache
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_os_family == "RedHat"
  become: true

- name: Install build requirements for RH based distros
  ansible.builtin.dnf:
    name: 
    - git
    - ninja-build 
    - libtool 
    - autoconf 
    - automake 
    - cmake 
    - gcc
    - gcc-c++ 
    - make 
    - pkgconfig 
    - unzip 
    - patch 
    - gettext 
    - curl
    - fontconfig
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Install build requirements for Debian Based Systems
  ansible.builtin.apt:
    name: 
    - git
    - ninja-build 
    - gettext 
    - libtool 
    - libtool-bin 
    - autoconf 
    - automake 
    - cmake 
    - g++ 
    - pkg-config 
    - unzip 
    - curl 
    - doxygen
    - fontconfig
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Remove any previous build artifacts
  ansible.builtin.file:
    path: /tmp/neovim
    state: absent
  become: true

- name: Clone the neovim repository
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    clone: true
    dest: /tmp/neovim
    depth: 1
    creates: /tmp/neovim

- name: Build Neovim CMAKE_BUILD_TYPE=RelWithDebInfo
  ansible.builtin.command:
    chdir: /tmp/neovim
    cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
    

